- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections:
    - netap.ontap 
  tasks:
  - name: stopping svm {{ src_svm }} on {{ src_cluster }}
    na_ontap_command:
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      command: ['vserver stop {{ src_svm }}']
      
  - name: waiting for svm status stopped for{{ src_cluster }} / {{ src_svm }}
    na_ontap_command:
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      command: ['vserver show prod -fields operational-state']
      return_dict: true
    register: src_svmstatus
    until: svmbreakstatus.msg.stdout.find("Quiesced") != -1
    retries: 12
    delay: 30
    
  - name: return svm-dr status
    debug:
       msg : "{{ svmdrstatus.msg.stdout_lines[2].split()[1] }}"